export const dataProperties = [
  {
    id: 1,
    location: "Bogotá - Colombia ",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpg",
    star: 4.5,
    meters: 430,
    description:
      "En la encantadora y bellísima bogotá se encuentra esta grandiosa casa de dos pisos, con multiples ventanales y jardínes bellísimos",
  },
  {
    id: 2,
    location: "Medellín - Colombia",
    price: 300000000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpg",
    star: 4,
    meters: 230,
    description:
      "Medellín la tierra encantandora, en sus albergues se encuentra esta hermosa casa esquinera de dos pisos en color blanco, con multiples ventanales y una vista increíble",
  },
  {
    id: 3,
    location: "Pereira - Colombia",
    price: 150000000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.webp",
    star: 5,
    meters: 90,
    description:
      "En la hermosa, querendona y transnochadora perla del otún, se encuentra esta hermosa con su jardín y su respectiva psicina la cuál la hace ideal para un plan familiar ",
  },
  {
    id: 4,
    location: "Cali - Colombia",
    price: 180000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpg",
    star: 4.2,
    meters: 120,
    description:
      "Cali, la ciudad de la salsa, en esta hermosa ciudad se encuentra la casa de los sueños, construida en dos pisos con multiples ventalanes para mayor confort",
  },
  {
    id: 5,
    location: "Santa marta - Colombia",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpg",
    star: 4.1,
    meters: 87,
    description:
      "Santa marta, la ciudad del placer y el descanso, aquí se encuentra esta hermosa casa duplex, con amplios ventanales para mayor iluminación y confort",
  },
  {
    id: 6,
    location: "Ibagué - Colombia",
    price: 200000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpg",
    star: 3.7,
    meters: 220,
    description:
      "Ibagué, la ciudad del folclor y el baile, aquí se encuentra esta hermosa casa duplex, con su respectivo parqueadero para dos autos y/o todo tipo de vehículo.",
  },
  {
    id: 7,
    location: "Cartagena - Colombia",
    price: 250000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpg",
    star: 4.5,
    meters: 430,
    description:
      "En la espectacular ciudad de cartagena se ubica esta hermosa casa, con una pscina que harán de tus vacaciones las mejores.",
  },
  {
    id: 8,
    location: "San andrés - Colombia",
    price: 300000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpg",
    star: 4.5,
    meters: 330,
    description:
      "San andrés, sol, playa y arena; aquí se encuentra esta hermosa casa duplex con una vista inigualable y un confort indescriptible.",
  },
  {
    id: 9,
    location: "Manizales - Colombia",
    price: 250000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpg",
    star: 4.5,
    meters: 380,
    description:
      "En el corazón de manizales se encuentra esta hermosa casa, con su bella arquitectura y con su tema inspirado en el campo.",
  },
  {
    id: 10,
    location: "Pasto - Colombia",
    price: 150000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpg",
    star: 4.1,
    meters: 270,
    description:
      "Pasto, la ciudad del buen sabor y sazón. Rodeada de hermosas montañas y valles, aquí se encuentra esta hermosa casa colorida mostrando la vida.",
  },
  {
    id: 11,
    location: "Bucaramanga - Colombia",
    price: 270000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.webp",
    star: 5,
    meters: 430,
    description:
      "En la hermosa ciudad de bucaramanga se encuentra esta hermosa casa, con un concepto minimalista y colores neutros. Resaltando su diseño de arquitectura.",
  },
  {
    id: 12,
    location: "Villavicencio - Colombia",
    price: 160000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpg",
    star: 3.9,
    meters: 76,
    description:
      "En la hermosa ciudad de villavicencio se encuentra en medio del campo esta hermosa casa, inspirada en la recreación y el descanso familiar.",
  },
  {
    id: 13,
    location: "Valledupar - Colombia",
    price: 230000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.webp",
    star: 4.8,
    meters: 290,
    description:
      "Valledupar, la tierra del vallenato y de los soles intensos, aquí se encuentra esta hermosa casa duplex con un concepto minimalista, conservando la elegancia,",
  },
  {
    id: 14,
    location: "Yumbo - Colombia",
    price: 210000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.webp",
    star: 4.9,
    meters: 180,
    description:
      "El valle, aquí en yumbo se encuentra esta magnifica vivienda, con un estilo minimalista y con unos acabados impecables, Rodeada de naturaleza.",
  },
  {
    id: 15,
    location: "Pereira - Colombia",
    price: 300000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "Pereira, aquí se encuentra esta hermosa vivienda, úbicada en cerritos, rodeada de naturaleza y conservando la arquitectura inicial.",
  },
  {
    id: 16,
    location: "Armenia - Colombia",
    price: 280000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpg",
    star: 4,
    meters: 290,
    description:
      "En la hermosa ciudad del quindío, se encuentra esta vivienda. Con un estilo único e inigualable. ",
  },
];
